version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: password
      TYPEORM_DATABASE: wallet
      TYPEORM_SYNCHRONIZE: true
      TYPEORM_ENTITIES: dist/**/*.entity.js
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  db-data:
